version: '3.8'

services:
  api-nestjs:
    build:
      context: ./api-nestjs
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./api-nestjs/.env.docker
    environment:
      - PORT=3000
    depends_on:
      - postgres
    # O comando foi movido para o docker-entrypoint.sh para garantir que o banco de dados esteja pronto

  frontend-angular:
    build:
      context: ./front-angular
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    depends_on:
      - api-nestjs

  postgres:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-cds-bot}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  n8n:
    image: n8nio/n8n
    ports:
      - "5678:5678"
    environment:
      - GENERIC_TIMEZONE=${GENERIC_TIMEZONE:-America/Sao_Paulo}
    volumes:
      - n8n_data:/home/node/.n8n

volumes:
  postgres_data:
  n8n_data:
